name: Build Debug Probe

on:
  workflow_dispatch:   # allows manual trigger in UI
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi cmake ninja-build

    - name: Build debugprobe for Pico
      run: |
        mkdir build
        cd build
        cmake -DDEBUG_ON_PICO=ON -G Ninja ..
        ninja

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-uf2
        path: build/*.uf2
